### ISSUE TITLE
HTML stripped on purpose?

### ISSUE THREAD

**Issue by glueckpress** [barrykooij/wp-notification-center#7]
Having fun with [this](https://gist.github.com/glueckpress/26b791ab52d5c197ef0c) I noticed HTML ([line breaks](https://gist.github.com/glueckpress/26b791ab52d5c197ef0c/ba48197530f7bbb7aad4faa0af29fadded2ca47d#file-notifications-ffs-php-L44), [links](https://gist.github.com/glueckpress/26b791ab52d5c197ef0c/56fc074032d590fe8f659fdc9d7a586323fd0c90#file-notifications-ffs-php-L40)) get stripped out of the notice text. 
Bug or feature?

**Comment by 4nickpick** [comment]
Second, I'd like links to persist.

**Comment by 4nickpick** [comment]
I see it's been implemented as a menu item, with the link set to `false`. If we could extract the first href in the content of the notification and use that as the menu item link that would be fantastic. 

Of course, that means some DOM parsing which might be more heavyweight than you're willing to allow this plugin to get. Maybe WP has a built-in?

**Comment by glueckpress** [comment]
Closing this, [see here](https://github.com/barrykooij/wp-notification-center/issues/8#issuecomment-731409786).
