### ISSUE TITLE
Idea: generate sample notification after plugin activation?

### ISSUE THREAD

**Issue by glueckpress** [barrykooij/wp-notification-center#8]
Derived of this conversation on [Twitter](https://twitter.com/benjaminlupu/status/644164094497529856), how about a generated sample notification after the plugin has been activated for the first time? Something light and encouraging, will gladly help out with copy if you like the idea.

**Comment by JJJ** [comment]
This is a good idea, because after you activate the plugin, regular notices like "Plugin activated." still appear in their normal place, which makes it not very obvious what it's for.

**Comment by glueckpress** [comment]
As the plugin does not seem to be actively maintained and I’m on an issue closing spree, I am closing this off. Hope you’re fine, @JJJ, take good care! 👋🏼 🙂
